# Generated by Django 4.2.6 on 2023-12-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_mobile_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
