# Generated by Django 4.2.6 on 2023-12-16 18:34

from django.db import migrations
import phonenumber_field.modelfields
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_customer_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, validators=[store.validators.validate_possible_number]),
        ),
    ]
